#services:
#  mysql:
#    image: mysql:latest
#    environment:
#      - MYSQL_DATABASE=antiheimer
#      - MYSQL_ROOT_PASSWORD=qwer1234
#      - 'MYSQL_USER=myuser'
#    command: # 명령어 실행
#      - --character-set-server=utf8mb4
#      - --collation-server=utf8mb4_unicode_ci
#
#    ports:
#      - 3306
