spring:
  datasource:
    url: jdbc:mysql://mysql-container:3306/antiheimer
    username: root
    password: qwer1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    root:
    org.hibernate.SQL: debug
    #org.hibernate.orm.jdbc.bind: trace

springdoc:
  swagger-ui:
    enabled: true # swagger ui 사용여부 (굳이 설정하지 않아도 default는 true)
    path: /swagger-ui.html
  version: 'v1' # API 문서 버전
  default-consumes-media-type: application/json # 기본 consume media type
  default-produces-media-type: application/json # 기본 produce media type
  model-and-view-allowed: true # ModelAndView 허용

jwt:
  access-token-expiration: 360000 # 1시간
  refresh-token-expirationL: 86400000 # 1일
  secret: 3e5e34caed03f76c6510fe14b89a1e56bb239acb9085351baa21a068f10f9236


server:
  port: 8081
  address: 0.0.0.0

auth:
  key: "아직몰라"