spring:
  datasource:
    url: jdbc:mysql://mysql-container:3306/antiheimer
    username: root
    password: qwer1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    root:
    org.hibernate.SQL: debug
    #org.hibernate.orm.jdbc.bind: trace

auth:
  key: ""

server:
  port: 8080
  address: 0.0.0.0